# Generated by Django 2.2.4 on 2019-08-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0010_auto_20190823_1057'),
        ('users', '0002_customuser_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='airline.Ticket'),
        ),
    ]
