# Generated by Django 2.2.4 on 2019-08-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': "Aircraft's Name",
                'verbose_name_plural': "Aircraft's Names",
            },
        ),
        migrations.AlterModelOptions(
            name='aircraft',
            options={'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircraft'},
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='title',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='airline.AircraftName'),
        ),
    ]
