# Generated by Django 2.2.4 on 2019-08-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20190820_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='airline.AircraftName'),
        ),
    ]
