# Generated by Django 2.2.4 on 2019-08-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_auto_20190820_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': "Aircraft's Model",
                'verbose_name_plural': "Aircraft's Model",
            },
        ),
        migrations.AlterField(
            model_name='aircraftname',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='airline.AircraftModel'),
        ),
    ]
