# Generated by Django 2.2.4 on 2019-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_auto_20190820_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='title',
        ),
        migrations.RemoveField(
            model_name='country',
            name='title',
        ),
        migrations.RemoveField(
            model_name='region',
            name='title',
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
