# Generated by Django 2.2.4 on 2019-08-20 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_auto_20190820_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='passport_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_series',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
