# Generated by Django 2.2.4 on 2019-08-20 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0007_auto_20190820_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='passport_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('\\d{4}')]),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_series',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('\\d{4}')]),
        ),
    ]
