# Generated by Django 2.2.4 on 2019-08-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_auto_20190820_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.Passport'),
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
